### ISSUE TITLE
Unclear error message for sla-agent

### ISSUE THREAD

**Issue by Anonstake** [skalenetwork/sla-agent#111]
Hello,

After the current testnet soft upgrade, I am getting error messages on telegram notifications. Node is in maintenance mode.
Error:

:bangbang: Container: sla-agent, Node: Anonstake2, ID: 32, IP: xx.xx.xx.xx

Error occurred during monitoring job: list.remove(x): x not in list

Timestamp: 1611162687
Datetime: Wed Jan 20 17:11:27 2021

I find the error message ( monitoring job: list.remove(x): x not in list ) unclear.

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3790)

**Comment by cstrangedk** [comment]
@Anonstake thanks for reporting. Please disregard the error as there is no impact on your behalf. The Network is deprecating sla-agent in favor of a new validator-based monitoring system that's in the works. Feel free to open if there are any additional concerns.
